/**
 * 此文件由脚本自动生成，请勿直接修改
 */
export const CITIES = [
  {
    code: '110000',
    name: '北京市',
    shortName: '北京',
    pinyin: 'beijingshi',
    pinyinFirstLetter: 'bjs',
  },
  {
    code: '120000',
    name: '天津市',
    shortName: '天津',
    pinyin: 'tianjinshi',
    pinyinFirstLetter: 'tjs',
  },
  {
    code: '130000',
    name: '河北省',
    shortName: '河北',
    pinyin: 'hebeisheng',
    pinyinFirstLetter: 'hbs',
  },
  {
    code: '130100',
    name: '石家庄市',
    shortName: '石家庄',
    pinyin: 'shijiazhuangshi',
    pinyinFirstLetter: 'sjzs',
  },
  {
    code: '130200',
    name: '唐山市',
    shortName: '唐山',
    pinyin: 'tangshanshi',
    pinyinFirstLetter: 'tss',
  },
  {
    code: '130300',
    name: '秦皇岛市',
    shortName: '秦皇岛',
    pinyin: 'qinhuangdaoshi',
    pinyinFirstLetter: 'qhds',
  },
  {
    code: '130400',
    name: '邯郸市',
    shortName: '邯郸',
    pinyin: 'handanshi',
    pinyinFirstLetter: 'hds',
  },
  {
    code: '130500',
    name: '邢台市',
    shortName: '邢台',
    pinyin: 'xingtaishi',
    pinyinFirstLetter: 'xts',
  },
  {
    code: '130600',
    name: '保定市',
    shortName: '保定',
    pinyin: 'baodingshi',
    pinyinFirstLetter: 'bds',
  },
  {
    code: '130700',
    name: '张家口市',
    shortName: '张家口',
    pinyin: 'zhangjiakoushi',
    pinyinFirstLetter: 'zjks',
  },
  {
    code: '130800',
    name: '承德市',
    shortName: '承德',
    pinyin: 'chengdeshi',
    pinyinFirstLetter: 'cds',
  },
  {
    code: '130900',
    name: '沧州市',
    shortName: '沧州',
    pinyin: 'cangzhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '131000',
    name: '廊坊市',
    shortName: '廊坊',
    pinyin: 'langfangshi',
    pinyinFirstLetter: 'lfs',
  },
  {
    code: '131100',
    name: '衡水市',
    shortName: '衡水',
    pinyin: 'hengshuishi',
    pinyinFirstLetter: 'hss',
  },
  {
    code: '140000',
    name: '山西省',
    shortName: '山西',
    pinyin: 'shanxisheng',
    pinyinFirstLetter: 'sxs',
  },
  {
    code: '140100',
    name: '太原市',
    shortName: '太原',
    pinyin: 'taiyuanshi',
    pinyinFirstLetter: 'tys',
  },
  {
    code: '140200',
    name: '大同市',
    shortName: '大同',
    pinyin: 'datongshi',
    pinyinFirstLetter: 'dts',
  },
  {
    code: '140300',
    name: '阳泉市',
    shortName: '阳泉',
    pinyin: 'yangquanshi',
    pinyinFirstLetter: 'yqs',
  },
  {
    code: '140400',
    name: '长治市',
    shortName: '长治',
    pinyin: 'changzhishi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '140500',
    name: '晋城市',
    shortName: '晋城',
    pinyin: 'jinchengshi',
    pinyinFirstLetter: 'jcs',
  },
  {
    code: '140600',
    name: '朔州市',
    shortName: '朔州',
    pinyin: 'shuozhoushi',
    pinyinFirstLetter: 'szs',
  },
  {
    code: '140700',
    name: '晋中市',
    shortName: '晋中',
    pinyin: 'jinzhongshi',
    pinyinFirstLetter: 'jzs',
  },
  {
    code: '140800',
    name: '运城市',
    shortName: '运城',
    pinyin: 'yunchengshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '140900',
    name: '忻州市',
    shortName: '忻州',
    pinyin: 'xinzhoushi',
    pinyinFirstLetter: 'xzs',
  },
  {
    code: '141000',
    name: '临汾市',
    shortName: '临汾',
    pinyin: 'linfenshi',
    pinyinFirstLetter: 'lfs',
  },
  {
    code: '141100',
    name: '吕梁市',
    shortName: '吕梁',
    pinyin: 'lvliangshi',
    pinyinFirstLetter: 'lls',
  },
  {
    code: '150000',
    name: '内蒙古自治区',
    shortName: '内蒙古',
    pinyin: 'neimengguzizhiqu',
    pinyinFirstLetter: 'nmgzzq',
  },
  {
    code: '150100',
    name: '呼和浩特市',
    shortName: '呼和浩特',
    pinyin: 'huhehaoteshi',
    pinyinFirstLetter: 'hhhts',
  },
  {
    code: '150200',
    name: '包头市',
    shortName: '包头',
    pinyin: 'baotoushi',
    pinyinFirstLetter: 'bts',
  },
  {
    code: '150300',
    name: '乌海市',
    shortName: '乌海',
    pinyin: 'wuhaishi',
    pinyinFirstLetter: 'whs',
  },
  {
    code: '150400',
    name: '赤峰市',
    shortName: '赤峰',
    pinyin: 'chifengshi',
    pinyinFirstLetter: 'cfs',
  },
  {
    code: '150500',
    name: '通辽市',
    shortName: '通辽',
    pinyin: 'tongliaoshi',
    pinyinFirstLetter: 'tls',
  },
  {
    code: '150600',
    name: '鄂尔多斯市',
    shortName: '鄂尔多斯',
    pinyin: 'eerduosishi',
    pinyinFirstLetter: 'eedss',
  },
  {
    code: '150700',
    name: '呼伦贝尔市',
    shortName: '呼伦贝尔',
    pinyin: 'hulunbeiershi',
    pinyinFirstLetter: 'hlbes',
  },
  {
    code: '150800',
    name: '巴彦淖尔市',
    shortName: '巴彦淖尔',
    pinyin: 'bayannaoershi',
    pinyinFirstLetter: 'bynes',
  },
  {
    code: '150900',
    name: '乌兰察布市',
    shortName: '乌兰察布',
    pinyin: 'wulanchabushi',
    pinyinFirstLetter: 'wlcbs',
  },
  {
    code: '152200',
    name: '兴安盟',
    shortName: '兴安',
    pinyin: 'xinganmeng',
    pinyinFirstLetter: 'xam',
  },
  {
    code: '152500',
    name: '锡林郭勒盟',
    shortName: '锡林郭勒',
    pinyin: 'xilinguolemeng',
    pinyinFirstLetter: 'xlglm',
  },
  {
    code: '152900',
    name: '阿拉善盟',
    shortName: '阿拉善',
    pinyin: 'alashanmeng',
    pinyinFirstLetter: 'alsm',
  },
  {
    code: '210000',
    name: '辽宁省',
    shortName: '辽宁',
    pinyin: 'liaoningsheng',
    pinyinFirstLetter: 'lns',
  },
  {
    code: '210100',
    name: '沈阳市',
    shortName: '沈阳',
    pinyin: 'shenyangshi',
    pinyinFirstLetter: 'sys',
  },
  {
    code: '210200',
    name: '大连市',
    shortName: '大连',
    pinyin: 'dalianshi',
    pinyinFirstLetter: 'dls',
  },
  {
    code: '210300',
    name: '鞍山市',
    shortName: '鞍山',
    pinyin: 'anshanshi',
    pinyinFirstLetter: 'ass',
  },
  {
    code: '210400',
    name: '抚顺市',
    shortName: '抚顺',
    pinyin: 'fushunshi',
    pinyinFirstLetter: 'fss',
  },
  {
    code: '210500',
    name: '本溪市',
    shortName: '本溪',
    pinyin: 'benxishi',
    pinyinFirstLetter: 'bxs',
  },
  {
    code: '210600',
    name: '丹东市',
    shortName: '丹东',
    pinyin: 'dandongshi',
    pinyinFirstLetter: 'dds',
  },
  {
    code: '210700',
    name: '锦州市',
    shortName: '锦州',
    pinyin: 'jinzhoushi',
    pinyinFirstLetter: 'jzs',
  },
  {
    code: '210800',
    name: '营口市',
    shortName: '营口',
    pinyin: 'yingkoushi',
    pinyinFirstLetter: 'yks',
  },
  {
    code: '210900',
    name: '阜新市',
    shortName: '阜新',
    pinyin: 'fuxinshi',
    pinyinFirstLetter: 'fxs',
  },
  {
    code: '211000',
    name: '辽阳市',
    shortName: '辽阳',
    pinyin: 'liaoyangshi',
    pinyinFirstLetter: 'lys',
  },
  {
    code: '211100',
    name: '盘锦市',
    shortName: '盘锦',
    pinyin: 'panjinshi',
    pinyinFirstLetter: 'pjs',
  },
  {
    code: '211200',
    name: '铁岭市',
    shortName: '铁岭',
    pinyin: 'tielingshi',
    pinyinFirstLetter: 'tls',
  },
  {
    code: '211300',
    name: '朝阳市',
    shortName: '朝阳',
    pinyin: 'zhaoyangshi',
    pinyinFirstLetter: 'zys',
  },
  {
    code: '211400',
    name: '葫芦岛市',
    shortName: '葫芦岛',
    pinyin: 'huludaoshi',
    pinyinFirstLetter: 'hlds',
  },
  {
    code: '220000',
    name: '吉林省',
    shortName: '吉林',
    pinyin: 'jilinsheng',
    pinyinFirstLetter: 'jls',
  },
  {
    code: '220100',
    name: '长春市',
    shortName: '长春',
    pinyin: 'changchunshi',
    pinyinFirstLetter: 'ccs',
  },
  {
    code: '220200',
    name: '吉林市',
    shortName: '吉林',
    pinyin: 'jilinshi',
    pinyinFirstLetter: 'jls',
  },
  {
    code: '220300',
    name: '四平市',
    shortName: '四平',
    pinyin: 'sipingshi',
    pinyinFirstLetter: 'sps',
  },
  {
    code: '220400',
    name: '辽源市',
    shortName: '辽源',
    pinyin: 'liaoyuanshi',
    pinyinFirstLetter: 'lys',
  },
  {
    code: '220500',
    name: '通化市',
    shortName: '通化',
    pinyin: 'tonghuashi',
    pinyinFirstLetter: 'ths',
  },
  {
    code: '220600',
    name: '白山市',
    shortName: '白山',
    pinyin: 'baishanshi',
    pinyinFirstLetter: 'bss',
  },
  {
    code: '220700',
    name: '松原市',
    shortName: '松原',
    pinyin: 'songyuanshi',
    pinyinFirstLetter: 'sys',
  },
  {
    code: '220800',
    name: '白城市',
    shortName: '白城',
    pinyin: 'baichengshi',
    pinyinFirstLetter: 'bcs',
  },
  {
    code: '222400',
    name: '延边朝鲜族自治州',
    shortName: '延边',
    pinyin: 'yanbianzhaoxianzuzizhizhou',
    pinyinFirstLetter: 'ybzxzzzz',
  },
  {
    code: '230000',
    name: '黑龙江省',
    shortName: '黑龙江',
    pinyin: 'heilongjiangsheng',
    pinyinFirstLetter: 'hljs',
  },
  {
    code: '230100',
    name: '哈尔滨市',
    shortName: '哈尔滨',
    pinyin: 'haerbinshi',
    pinyinFirstLetter: 'hebs',
  },
  {
    code: '230200',
    name: '齐齐哈尔市',
    shortName: '齐齐哈尔',
    pinyin: 'qiqihaershi',
    pinyinFirstLetter: 'qqhes',
  },
  {
    code: '230300',
    name: '鸡西市',
    shortName: '鸡西',
    pinyin: 'jixishi',
    pinyinFirstLetter: 'jxs',
  },
  {
    code: '230400',
    name: '鹤岗市',
    shortName: '鹤岗',
    pinyin: 'hegangshi',
    pinyinFirstLetter: 'hgs',
  },
  {
    code: '230500',
    name: '双鸭山市',
    shortName: '双鸭山',
    pinyin: 'shuangyashanshi',
    pinyinFirstLetter: 'syss',
  },
  {
    code: '230600',
    name: '大庆市',
    shortName: '大庆',
    pinyin: 'daqingshi',
    pinyinFirstLetter: 'dqs',
  },
  {
    code: '230700',
    name: '伊春市',
    shortName: '伊春',
    pinyin: 'yichunshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '230800',
    name: '佳木斯市',
    shortName: '佳木斯',
    pinyin: 'jiamusishi',
    pinyinFirstLetter: 'jmss',
  },
  {
    code: '230900',
    name: '七台河市',
    shortName: '七台河',
    pinyin: 'qitaiheshi',
    pinyinFirstLetter: 'qths',
  },
  {
    code: '231000',
    name: '牡丹江市',
    shortName: '牡丹江',
    pinyin: 'mudanjiangshi',
    pinyinFirstLetter: 'mdjs',
  },
  {
    code: '231100',
    name: '黑河市',
    shortName: '黑河',
    pinyin: 'heiheshi',
    pinyinFirstLetter: 'hhs',
  },
  {
    code: '231200',
    name: '绥化市',
    shortName: '绥化',
    pinyin: 'suihuashi',
    pinyinFirstLetter: 'shs',
  },
  {
    code: '232700',
    name: '大兴安岭地区',
    shortName: '大兴安岭',
    pinyin: 'daxinganlingdiqu',
    pinyinFirstLetter: 'dxaldq',
  },
  {
    code: '310000',
    name: '上海市',
    shortName: '上海',
    pinyin: 'shanghaishi',
    pinyinFirstLetter: 'shs',
  },
  {
    code: '320000',
    name: '江苏省',
    shortName: '江苏',
    pinyin: 'jiangsusheng',
    pinyinFirstLetter: 'jss',
  },
  {
    code: '320100',
    name: '南京市',
    shortName: '南京',
    pinyin: 'nanjingshi',
    pinyinFirstLetter: 'njs',
  },
  {
    code: '320200',
    name: '无锡市',
    shortName: '无锡',
    pinyin: 'wuxishi',
    pinyinFirstLetter: 'wxs',
  },
  {
    code: '320300',
    name: '徐州市',
    shortName: '徐州',
    pinyin: 'xuzhoushi',
    pinyinFirstLetter: 'xzs',
  },
  {
    code: '320400',
    name: '常州市',
    shortName: '常州',
    pinyin: 'changzhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '320500',
    name: '苏州市',
    shortName: '苏州',
    pinyin: 'suzhoushi',
    pinyinFirstLetter: 'szs',
  },
  {
    code: '320600',
    name: '南通市',
    shortName: '南通',
    pinyin: 'nantongshi',
    pinyinFirstLetter: 'nts',
  },
  {
    code: '320700',
    name: '连云港市',
    shortName: '连云港',
    pinyin: 'lianyungangshi',
    pinyinFirstLetter: 'lygs',
  },
  {
    code: '320800',
    name: '淮安市',
    shortName: '淮安',
    pinyin: 'huaianshi',
    pinyinFirstLetter: 'has',
  },
  {
    code: '320900',
    name: '盐城市',
    shortName: '盐城',
    pinyin: 'yanchengshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '321000',
    name: '扬州市',
    shortName: '扬州',
    pinyin: 'yangzhoushi',
    pinyinFirstLetter: 'yzs',
  },
  {
    code: '321100',
    name: '镇江市',
    shortName: '镇江',
    pinyin: 'zhenjiangshi',
    pinyinFirstLetter: 'zjs',
  },
  {
    code: '321200',
    name: '泰州市',
    shortName: '泰州',
    pinyin: 'taizhoushi',
    pinyinFirstLetter: 'tzs',
  },
  {
    code: '321300',
    name: '宿迁市',
    shortName: '宿迁',
    pinyin: 'suqianshi',
    pinyinFirstLetter: 'sqs',
  },
  {
    code: '330000',
    name: '浙江省',
    shortName: '浙江',
    pinyin: 'zhejiangsheng',
    pinyinFirstLetter: 'zjs',
  },
  {
    code: '330100',
    name: '杭州市',
    shortName: '杭州',
    pinyin: 'hangzhoushi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '330200',
    name: '宁波市',
    shortName: '宁波',
    pinyin: 'ningboshi',
    pinyinFirstLetter: 'nbs',
  },
  {
    code: '330300',
    name: '温州市',
    shortName: '温州',
    pinyin: 'wenzhoushi',
    pinyinFirstLetter: 'wzs',
  },
  {
    code: '330400',
    name: '嘉兴市',
    shortName: '嘉兴',
    pinyin: 'jiaxingshi',
    pinyinFirstLetter: 'jxs',
  },
  {
    code: '330500',
    name: '湖州市',
    shortName: '湖州',
    pinyin: 'huzhoushi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '330600',
    name: '绍兴市',
    shortName: '绍兴',
    pinyin: 'shaoxingshi',
    pinyinFirstLetter: 'sxs',
  },
  {
    code: '330700',
    name: '金华市',
    shortName: '金华',
    pinyin: 'jinhuashi',
    pinyinFirstLetter: 'jhs',
  },
  {
    code: '330800',
    name: '衢州市',
    shortName: '衢州',
    pinyin: 'quzhoushi',
    pinyinFirstLetter: 'qzs',
  },
  {
    code: '330900',
    name: '舟山市',
    shortName: '舟山',
    pinyin: 'zhoushanshi',
    pinyinFirstLetter: 'zss',
  },
  {
    code: '331000',
    name: '台州市',
    shortName: '台州',
    pinyin: 'taizhoushi',
    pinyinFirstLetter: 'tzs',
  },
  {
    code: '331100',
    name: '丽水市',
    shortName: '丽水',
    pinyin: 'lishuishi',
    pinyinFirstLetter: 'lss',
  },
  {
    code: '340000',
    name: '安徽省',
    shortName: '安徽',
    pinyin: 'anhuisheng',
    pinyinFirstLetter: 'ahs',
  },
  {
    code: '340100',
    name: '合肥市',
    shortName: '合肥',
    pinyin: 'hefeishi',
    pinyinFirstLetter: 'hfs',
  },
  {
    code: '340200',
    name: '芜湖市',
    shortName: '芜湖',
    pinyin: 'wuhushi',
    pinyinFirstLetter: 'whs',
  },
  {
    code: '340300',
    name: '蚌埠市',
    shortName: '蚌埠',
    pinyin: 'bangbushi',
    pinyinFirstLetter: 'bbs',
  },
  {
    code: '340400',
    name: '淮南市',
    shortName: '淮南',
    pinyin: 'huainanshi',
    pinyinFirstLetter: 'hns',
  },
  {
    code: '340500',
    name: '马鞍山市',
    shortName: '马鞍山',
    pinyin: 'maanshanshi',
    pinyinFirstLetter: 'mass',
  },
  {
    code: '340600',
    name: '淮北市',
    shortName: '淮北',
    pinyin: 'huaibeishi',
    pinyinFirstLetter: 'hbs',
  },
  {
    code: '340700',
    name: '铜陵市',
    shortName: '铜陵',
    pinyin: 'tonglingshi',
    pinyinFirstLetter: 'tls',
  },
  {
    code: '340800',
    name: '安庆市',
    shortName: '安庆',
    pinyin: 'anqingshi',
    pinyinFirstLetter: 'aqs',
  },
  {
    code: '341000',
    name: '黄山市',
    shortName: '黄山',
    pinyin: 'huangshanshi',
    pinyinFirstLetter: 'hss',
  },
  {
    code: '341100',
    name: '滁州市',
    shortName: '滁州',
    pinyin: 'chuzhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '341200',
    name: '阜阳市',
    shortName: '阜阳',
    pinyin: 'fuyangshi',
    pinyinFirstLetter: 'fys',
  },
  {
    code: '341300',
    name: '宿州市',
    shortName: '宿州',
    pinyin: 'suzhoushi',
    pinyinFirstLetter: 'szs',
  },
  {
    code: '341500',
    name: '六安市',
    shortName: '六安',
    pinyin: 'liuanshi',
    pinyinFirstLetter: 'las',
  },
  {
    code: '341600',
    name: '亳州市',
    shortName: '亳州',
    pinyin: 'bozhoushi',
    pinyinFirstLetter: 'bzs',
  },
  {
    code: '341700',
    name: '池州市',
    shortName: '池州',
    pinyin: 'chizhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '341800',
    name: '宣城市',
    shortName: '宣城',
    pinyin: 'xuanchengshi',
    pinyinFirstLetter: 'xcs',
  },
  {
    code: '350000',
    name: '福建省',
    shortName: '福建',
    pinyin: 'fujiansheng',
    pinyinFirstLetter: 'fjs',
  },
  {
    code: '350100',
    name: '福州市',
    shortName: '福州',
    pinyin: 'fuzhoushi',
    pinyinFirstLetter: 'fzs',
  },
  {
    code: '350200',
    name: '厦门市',
    shortName: '厦门',
    pinyin: 'shamenshi',
    pinyinFirstLetter: 'sms',
  },
  {
    code: '350300',
    name: '莆田市',
    shortName: '莆田',
    pinyin: 'putianshi',
    pinyinFirstLetter: 'pts',
  },
  {
    code: '350400',
    name: '三明市',
    shortName: '三明',
    pinyin: 'sanmingshi',
    pinyinFirstLetter: 'sms',
  },
  {
    code: '350500',
    name: '泉州市',
    shortName: '泉州',
    pinyin: 'quanzhoushi',
    pinyinFirstLetter: 'qzs',
  },
  {
    code: '350600',
    name: '漳州市',
    shortName: '漳州',
    pinyin: 'zhangzhoushi',
    pinyinFirstLetter: 'zzs',
  },
  {
    code: '350700',
    name: '南平市',
    shortName: '南平',
    pinyin: 'nanpingshi',
    pinyinFirstLetter: 'nps',
  },
  {
    code: '350800',
    name: '龙岩市',
    shortName: '龙岩',
    pinyin: 'longyanshi',
    pinyinFirstLetter: 'lys',
  },
  {
    code: '350900',
    name: '宁德市',
    shortName: '宁德',
    pinyin: 'ningdeshi',
    pinyinFirstLetter: 'nds',
  },
  {
    code: '360000',
    name: '江西省',
    shortName: '江西',
    pinyin: 'jiangxisheng',
    pinyinFirstLetter: 'jxs',
  },
  {
    code: '360100',
    name: '南昌市',
    shortName: '南昌',
    pinyin: 'nanchangshi',
    pinyinFirstLetter: 'ncs',
  },
  {
    code: '360200',
    name: '景德镇市',
    shortName: '景德镇',
    pinyin: 'jingdezhenshi',
    pinyinFirstLetter: 'jdzs',
  },
  {
    code: '360300',
    name: '萍乡市',
    shortName: '萍乡',
    pinyin: 'pingxiangshi',
    pinyinFirstLetter: 'pxs',
  },
  {
    code: '360400',
    name: '九江市',
    shortName: '九江',
    pinyin: 'jiujiangshi',
    pinyinFirstLetter: 'jjs',
  },
  {
    code: '360500',
    name: '新余市',
    shortName: '新余',
    pinyin: 'xinyushi',
    pinyinFirstLetter: 'xys',
  },
  {
    code: '360600',
    name: '鹰潭市',
    shortName: '鹰潭',
    pinyin: 'yingtanshi',
    pinyinFirstLetter: 'yts',
  },
  {
    code: '360700',
    name: '赣州市',
    shortName: '赣州',
    pinyin: 'ganzhoushi',
    pinyinFirstLetter: 'gzs',
  },
  {
    code: '360800',
    name: '吉安市',
    shortName: '吉安',
    pinyin: 'jianshi',
    pinyinFirstLetter: 'jas',
  },
  {
    code: '360900',
    name: '宜春市',
    shortName: '宜春',
    pinyin: 'yichunshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '361000',
    name: '抚州市',
    shortName: '抚州',
    pinyin: 'fuzhoushi',
    pinyinFirstLetter: 'fzs',
  },
  {
    code: '361100',
    name: '上饶市',
    shortName: '上饶',
    pinyin: 'shangraoshi',
    pinyinFirstLetter: 'srs',
  },
  {
    code: '370000',
    name: '山东省',
    shortName: '山东',
    pinyin: 'shandongsheng',
    pinyinFirstLetter: 'sds',
  },
  {
    code: '370100',
    name: '济南市',
    shortName: '济南',
    pinyin: 'jinanshi',
    pinyinFirstLetter: 'jns',
  },
  {
    code: '370200',
    name: '青岛市',
    shortName: '青岛',
    pinyin: 'qingdaoshi',
    pinyinFirstLetter: 'qds',
  },
  {
    code: '370300',
    name: '淄博市',
    shortName: '淄博',
    pinyin: 'ziboshi',
    pinyinFirstLetter: 'zbs',
  },
  {
    code: '370400',
    name: '枣庄市',
    shortName: '枣庄',
    pinyin: 'zaozhuangshi',
    pinyinFirstLetter: 'zzs',
  },
  {
    code: '370500',
    name: '东营市',
    shortName: '东营',
    pinyin: 'dongyingshi',
    pinyinFirstLetter: 'dys',
  },
  {
    code: '370600',
    name: '烟台市',
    shortName: '烟台',
    pinyin: 'yantaishi',
    pinyinFirstLetter: 'yts',
  },
  {
    code: '370700',
    name: '潍坊市',
    shortName: '潍坊',
    pinyin: 'weifangshi',
    pinyinFirstLetter: 'wfs',
  },
  {
    code: '370800',
    name: '济宁市',
    shortName: '济宁',
    pinyin: 'jiningshi',
    pinyinFirstLetter: 'jns',
  },
  {
    code: '370900',
    name: '泰安市',
    shortName: '泰安',
    pinyin: 'taianshi',
    pinyinFirstLetter: 'tas',
  },
  {
    code: '371000',
    name: '威海市',
    shortName: '威海',
    pinyin: 'weihaishi',
    pinyinFirstLetter: 'whs',
  },
  {
    code: '371100',
    name: '日照市',
    shortName: '日照',
    pinyin: 'rizhaoshi',
    pinyinFirstLetter: 'rzs',
  },
  {
    code: '371300',
    name: '临沂市',
    shortName: '临沂',
    pinyin: 'linyishi',
    pinyinFirstLetter: 'lys',
  },
  {
    code: '371400',
    name: '德州市',
    shortName: '德州',
    pinyin: 'dezhoushi',
    pinyinFirstLetter: 'dzs',
  },
  {
    code: '371500',
    name: '聊城市',
    shortName: '聊城',
    pinyin: 'liaochengshi',
    pinyinFirstLetter: 'lcs',
  },
  {
    code: '371600',
    name: '滨州市',
    shortName: '滨州',
    pinyin: 'binzhoushi',
    pinyinFirstLetter: 'bzs',
  },
  {
    code: '371700',
    name: '菏泽市',
    shortName: '菏泽',
    pinyin: 'hezeshi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '410000',
    name: '河南省',
    shortName: '河南',
    pinyin: 'henansheng',
    pinyinFirstLetter: 'hns',
  },
  {
    code: '410100',
    name: '郑州市',
    shortName: '郑州',
    pinyin: 'zhengzhoushi',
    pinyinFirstLetter: 'zzs',
  },
  {
    code: '410200',
    name: '开封市',
    shortName: '开封',
    pinyin: 'kaifengshi',
    pinyinFirstLetter: 'kfs',
  },
  {
    code: '410300',
    name: '洛阳市',
    shortName: '洛阳',
    pinyin: 'luoyangshi',
    pinyinFirstLetter: 'lys',
  },
  {
    code: '410400',
    name: '平顶山市',
    shortName: '平顶山',
    pinyin: 'pingdingshanshi',
    pinyinFirstLetter: 'pdss',
  },
  {
    code: '410500',
    name: '安阳市',
    shortName: '安阳',
    pinyin: 'anyangshi',
    pinyinFirstLetter: 'ays',
  },
  {
    code: '410600',
    name: '鹤壁市',
    shortName: '鹤壁',
    pinyin: 'hebishi',
    pinyinFirstLetter: 'hbs',
  },
  {
    code: '410700',
    name: '新乡市',
    shortName: '新乡',
    pinyin: 'xinxiangshi',
    pinyinFirstLetter: 'xxs',
  },
  {
    code: '410800',
    name: '焦作市',
    shortName: '焦作',
    pinyin: 'jiaozuoshi',
    pinyinFirstLetter: 'jzs',
  },
  {
    code: '410900',
    name: '濮阳市',
    shortName: '濮阳',
    pinyin: 'puyangshi',
    pinyinFirstLetter: 'pys',
  },
  {
    code: '411000',
    name: '许昌市',
    shortName: '许昌',
    pinyin: 'xuchangshi',
    pinyinFirstLetter: 'xcs',
  },
  {
    code: '411100',
    name: '漯河市',
    shortName: '漯河',
    pinyin: 'luoheshi',
    pinyinFirstLetter: 'lhs',
  },
  {
    code: '411200',
    name: '三门峡市',
    shortName: '三门峡',
    pinyin: 'sanmenxiashi',
    pinyinFirstLetter: 'smxs',
  },
  {
    code: '411300',
    name: '南阳市',
    shortName: '南阳',
    pinyin: 'nanyangshi',
    pinyinFirstLetter: 'nys',
  },
  {
    code: '411400',
    name: '商丘市',
    shortName: '商丘',
    pinyin: 'shangqiushi',
    pinyinFirstLetter: 'sqs',
  },
  {
    code: '411500',
    name: '信阳市',
    shortName: '信阳',
    pinyin: 'xinyangshi',
    pinyinFirstLetter: 'xys',
  },
  {
    code: '411600',
    name: '周口市',
    shortName: '周口',
    pinyin: 'zhoukoushi',
    pinyinFirstLetter: 'zks',
  },
  {
    code: '411700',
    name: '驻马店市',
    shortName: '驻马店',
    pinyin: 'zhumadianshi',
    pinyinFirstLetter: 'zmds',
  },
  {
    code: '420000',
    name: '湖北省',
    shortName: '湖北',
    pinyin: 'hubeisheng',
    pinyinFirstLetter: 'hbs',
  },
  {
    code: '420100',
    name: '武汉市',
    shortName: '武汉',
    pinyin: 'wuhanshi',
    pinyinFirstLetter: 'whs',
  },
  {
    code: '420200',
    name: '黄石市',
    shortName: '黄石',
    pinyin: 'huangshishi',
    pinyinFirstLetter: 'hss',
  },
  {
    code: '420300',
    name: '十堰市',
    shortName: '十堰',
    pinyin: 'shiyanshi',
    pinyinFirstLetter: 'sys',
  },
  {
    code: '420500',
    name: '宜昌市',
    shortName: '宜昌',
    pinyin: 'yichangshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '420600',
    name: '襄阳市',
    shortName: '襄阳',
    pinyin: 'xiangyangshi',
    pinyinFirstLetter: 'xys',
  },
  {
    code: '420700',
    name: '鄂州市',
    shortName: '鄂州',
    pinyin: 'ezhoushi',
    pinyinFirstLetter: 'ezs',
  },
  {
    code: '420800',
    name: '荆门市',
    shortName: '荆门',
    pinyin: 'jingmenshi',
    pinyinFirstLetter: 'jms',
  },
  {
    code: '420900',
    name: '孝感市',
    shortName: '孝感',
    pinyin: 'xiaoganshi',
    pinyinFirstLetter: 'xgs',
  },
  {
    code: '421000',
    name: '荆州市',
    shortName: '荆州',
    pinyin: 'jingzhoushi',
    pinyinFirstLetter: 'jzs',
  },
  {
    code: '421100',
    name: '黄冈市',
    shortName: '黄冈',
    pinyin: 'huanggangshi',
    pinyinFirstLetter: 'hgs',
  },
  {
    code: '421200',
    name: '咸宁市',
    shortName: '咸宁',
    pinyin: 'xianningshi',
    pinyinFirstLetter: 'xns',
  },
  {
    code: '421300',
    name: '随州市',
    shortName: '随州',
    pinyin: 'suizhoushi',
    pinyinFirstLetter: 'szs',
  },
  {
    code: '422800',
    name: '恩施土家族苗族自治州',
    shortName: '恩施',
    pinyin: 'enshitujiazumiaozuzizhizhou',
    pinyinFirstLetter: 'estjzmzzzz',
  },
  {
    code: '430000',
    name: '湖南省',
    shortName: '湖南',
    pinyin: 'hunansheng',
    pinyinFirstLetter: 'hns',
  },
  {
    code: '430100',
    name: '长沙市',
    shortName: '长沙',
    pinyin: 'changshashi',
    pinyinFirstLetter: 'css',
  },
  {
    code: '430200',
    name: '株洲市',
    shortName: '株洲',
    pinyin: 'zhuzhoushi',
    pinyinFirstLetter: 'zzs',
  },
  {
    code: '430300',
    name: '湘潭市',
    shortName: '湘潭',
    pinyin: 'xiangtanshi',
    pinyinFirstLetter: 'xts',
  },
  {
    code: '430400',
    name: '衡阳市',
    shortName: '衡阳',
    pinyin: 'hengyangshi',
    pinyinFirstLetter: 'hys',
  },
  {
    code: '430500',
    name: '邵阳市',
    shortName: '邵阳',
    pinyin: 'shaoyangshi',
    pinyinFirstLetter: 'sys',
  },
  {
    code: '430600',
    name: '岳阳市',
    shortName: '岳阳',
    pinyin: 'yueyangshi',
    pinyinFirstLetter: 'yys',
  },
  {
    code: '430700',
    name: '常德市',
    shortName: '常德',
    pinyin: 'changdeshi',
    pinyinFirstLetter: 'cds',
  },
  {
    code: '430800',
    name: '张家界市',
    shortName: '张家界',
    pinyin: 'zhangjiajieshi',
    pinyinFirstLetter: 'zjjs',
  },
  {
    code: '430900',
    name: '益阳市',
    shortName: '益阳',
    pinyin: 'yiyangshi',
    pinyinFirstLetter: 'yys',
  },
  {
    code: '431000',
    name: '郴州市',
    shortName: '郴州',
    pinyin: 'chenzhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '431100',
    name: '永州市',
    shortName: '永州',
    pinyin: 'yongzhoushi',
    pinyinFirstLetter: 'yzs',
  },
  {
    code: '431200',
    name: '怀化市',
    shortName: '怀化',
    pinyin: 'huaihuashi',
    pinyinFirstLetter: 'hhs',
  },
  {
    code: '431300',
    name: '娄底市',
    shortName: '娄底',
    pinyin: 'loudishi',
    pinyinFirstLetter: 'lds',
  },
  {
    code: '433100',
    name: '湘西土家族苗族自治州',
    shortName: '湘西',
    pinyin: 'xiangxitujiazumiaozuzizhizhou',
    pinyinFirstLetter: 'xxtjzmzzzz',
  },
  {
    code: '440000',
    name: '广东省',
    shortName: '广东',
    pinyin: 'guangdongsheng',
    pinyinFirstLetter: 'gds',
  },
  {
    code: '440100',
    name: '广州市',
    shortName: '广州',
    pinyin: 'guangzhoushi',
    pinyinFirstLetter: 'gzs',
  },
  {
    code: '440200',
    name: '韶关市',
    shortName: '韶关',
    pinyin: 'shaoguanshi',
    pinyinFirstLetter: 'sgs',
  },
  {
    code: '440300',
    name: '深圳市',
    shortName: '深圳',
    pinyin: 'shenzhenshi',
    pinyinFirstLetter: 'szs',
  },
  {
    code: '440400',
    name: '珠海市',
    shortName: '珠海',
    pinyin: 'zhuhaishi',
    pinyinFirstLetter: 'zhs',
  },
  {
    code: '440500',
    name: '汕头市',
    shortName: '汕头',
    pinyin: 'shantoushi',
    pinyinFirstLetter: 'sts',
  },
  {
    code: '440600',
    name: '佛山市',
    shortName: '佛山',
    pinyin: 'foshanshi',
    pinyinFirstLetter: 'fss',
  },
  {
    code: '440700',
    name: '江门市',
    shortName: '江门',
    pinyin: 'jiangmenshi',
    pinyinFirstLetter: 'jms',
  },
  {
    code: '440800',
    name: '湛江市',
    shortName: '湛江',
    pinyin: 'zhanjiangshi',
    pinyinFirstLetter: 'zjs',
  },
  {
    code: '440900',
    name: '茂名市',
    shortName: '茂名',
    pinyin: 'maomingshi',
    pinyinFirstLetter: 'mms',
  },
  {
    code: '441200',
    name: '肇庆市',
    shortName: '肇庆',
    pinyin: 'zhaoqingshi',
    pinyinFirstLetter: 'zqs',
  },
  {
    code: '441300',
    name: '惠州市',
    shortName: '惠州',
    pinyin: 'huizhoushi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '441400',
    name: '梅州市',
    shortName: '梅州',
    pinyin: 'meizhoushi',
    pinyinFirstLetter: 'mzs',
  },
  {
    code: '441500',
    name: '汕尾市',
    shortName: '汕尾',
    pinyin: 'shanweishi',
    pinyinFirstLetter: 'sws',
  },
  {
    code: '441600',
    name: '河源市',
    shortName: '河源',
    pinyin: 'heyuanshi',
    pinyinFirstLetter: 'hys',
  },
  {
    code: '441700',
    name: '阳江市',
    shortName: '阳江',
    pinyin: 'yangjiangshi',
    pinyinFirstLetter: 'yjs',
  },
  {
    code: '441800',
    name: '清远市',
    shortName: '清远',
    pinyin: 'qingyuanshi',
    pinyinFirstLetter: 'qys',
  },
  {
    code: '441900',
    name: '东莞市',
    shortName: '东莞',
    pinyin: 'dongguanshi',
    pinyinFirstLetter: 'dgs',
  },
  {
    code: '442000',
    name: '中山市',
    shortName: '中山',
    pinyin: 'zhongshanshi',
    pinyinFirstLetter: 'zss',
  },
  {
    code: '445100',
    name: '潮州市',
    shortName: '潮州',
    pinyin: 'chaozhoushi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '445200',
    name: '揭阳市',
    shortName: '揭阳',
    pinyin: 'jieyangshi',
    pinyinFirstLetter: 'jys',
  },
  {
    code: '445300',
    name: '云浮市',
    shortName: '云浮',
    pinyin: 'yunfushi',
    pinyinFirstLetter: 'yfs',
  },
  {
    code: '450000',
    name: '广西壮族自治区',
    shortName: '广西',
    pinyin: 'guangxizhuangzuzizhiqu',
    pinyinFirstLetter: 'gxzzzzq',
  },
  {
    code: '450100',
    name: '南宁市',
    shortName: '南宁',
    pinyin: 'nanningshi',
    pinyinFirstLetter: 'nns',
  },
  {
    code: '450200',
    name: '柳州市',
    shortName: '柳州',
    pinyin: 'liuzhoushi',
    pinyinFirstLetter: 'lzs',
  },
  {
    code: '450300',
    name: '桂林市',
    shortName: '桂林',
    pinyin: 'guilinshi',
    pinyinFirstLetter: 'gls',
  },
  {
    code: '450400',
    name: '梧州市',
    shortName: '梧州',
    pinyin: 'wuzhoushi',
    pinyinFirstLetter: 'wzs',
  },
  {
    code: '450500',
    name: '北海市',
    shortName: '北海',
    pinyin: 'beihaishi',
    pinyinFirstLetter: 'bhs',
  },
  {
    code: '450600',
    name: '防城港市',
    shortName: '防城港',
    pinyin: 'fangchenggangshi',
    pinyinFirstLetter: 'fcgs',
  },
  {
    code: '450700',
    name: '钦州市',
    shortName: '钦州',
    pinyin: 'qinzhoushi',
    pinyinFirstLetter: 'qzs',
  },
  {
    code: '450800',
    name: '贵港市',
    shortName: '贵港',
    pinyin: 'guigangshi',
    pinyinFirstLetter: 'ggs',
  },
  {
    code: '450900',
    name: '玉林市',
    shortName: '玉林',
    pinyin: 'yulinshi',
    pinyinFirstLetter: 'yls',
  },
  {
    code: '451000',
    name: '百色市',
    shortName: '百色',
    pinyin: 'baiseshi',
    pinyinFirstLetter: 'bss',
  },
  {
    code: '451100',
    name: '贺州市',
    shortName: '贺州',
    pinyin: 'hezhoushi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '451200',
    name: '河池市',
    shortName: '河池',
    pinyin: 'hechishi',
    pinyinFirstLetter: 'hcs',
  },
  {
    code: '451300',
    name: '来宾市',
    shortName: '来宾',
    pinyin: 'laibinshi',
    pinyinFirstLetter: 'lbs',
  },
  {
    code: '451400',
    name: '崇左市',
    shortName: '崇左',
    pinyin: 'chongzuoshi',
    pinyinFirstLetter: 'czs',
  },
  {
    code: '460000',
    name: '海南省',
    shortName: '海南',
    pinyin: 'hainansheng',
    pinyinFirstLetter: 'hns',
  },
  {
    code: '460100',
    name: '海口市',
    shortName: '海口',
    pinyin: 'haikoushi',
    pinyinFirstLetter: 'hks',
  },
  {
    code: '460200',
    name: '三亚市',
    shortName: '三亚',
    pinyin: 'sanyashi',
    pinyinFirstLetter: 'sys',
  },
  {
    code: '460300',
    name: '三沙市',
    shortName: '三沙',
    pinyin: 'sanshashi',
    pinyinFirstLetter: 'sss',
  },
  {
    code: '460400',
    name: '儋州市',
    shortName: '儋州',
    pinyin: 'danzhoushi',
    pinyinFirstLetter: 'dzs',
  },
  {
    code: '500000',
    name: '重庆市',
    shortName: '重庆',
    pinyin: 'zhongqingshi',
    pinyinFirstLetter: 'zqs',
  },
  {
    code: '510000',
    name: '四川省',
    shortName: '四川',
    pinyin: 'sichuansheng',
    pinyinFirstLetter: 'scs',
  },
  {
    code: '510100',
    name: '成都市',
    shortName: '成都',
    pinyin: 'chengdushi',
    pinyinFirstLetter: 'cds',
  },
  {
    code: '510300',
    name: '自贡市',
    shortName: '自贡',
    pinyin: 'zigongshi',
    pinyinFirstLetter: 'zgs',
  },
  {
    code: '510400',
    name: '攀枝花市',
    shortName: '攀枝花',
    pinyin: 'panzhihuashi',
    pinyinFirstLetter: 'pzhs',
  },
  {
    code: '510500',
    name: '泸州市',
    shortName: '泸州',
    pinyin: 'luzhoushi',
    pinyinFirstLetter: 'lzs',
  },
  {
    code: '510600',
    name: '德阳市',
    shortName: '德阳',
    pinyin: 'deyangshi',
    pinyinFirstLetter: 'dys',
  },
  {
    code: '510700',
    name: '绵阳市',
    shortName: '绵阳',
    pinyin: 'mianyangshi',
    pinyinFirstLetter: 'mys',
  },
  {
    code: '510800',
    name: '广元市',
    shortName: '广元',
    pinyin: 'guangyuanshi',
    pinyinFirstLetter: 'gys',
  },
  {
    code: '510900',
    name: '遂宁市',
    shortName: '遂宁',
    pinyin: 'suiningshi',
    pinyinFirstLetter: 'sns',
  },
  {
    code: '511000',
    name: '内江市',
    shortName: '内江',
    pinyin: 'neijiangshi',
    pinyinFirstLetter: 'njs',
  },
  {
    code: '511100',
    name: '乐山市',
    shortName: '乐山',
    pinyin: 'leshanshi',
    pinyinFirstLetter: 'lss',
  },
  {
    code: '511300',
    name: '南充市',
    shortName: '南充',
    pinyin: 'nanchongshi',
    pinyinFirstLetter: 'ncs',
  },
  {
    code: '511400',
    name: '眉山市',
    shortName: '眉山',
    pinyin: 'meishanshi',
    pinyinFirstLetter: 'mss',
  },
  {
    code: '511500',
    name: '宜宾市',
    shortName: '宜宾',
    pinyin: 'yibinshi',
    pinyinFirstLetter: 'ybs',
  },
  {
    code: '511600',
    name: '广安市',
    shortName: '广安',
    pinyin: 'guanganshi',
    pinyinFirstLetter: 'gas',
  },
  {
    code: '511700',
    name: '达州市',
    shortName: '达州',
    pinyin: 'dazhoushi',
    pinyinFirstLetter: 'dzs',
  },
  {
    code: '511800',
    name: '雅安市',
    shortName: '雅安',
    pinyin: 'yaanshi',
    pinyinFirstLetter: 'yas',
  },
  {
    code: '511900',
    name: '巴中市',
    shortName: '巴中',
    pinyin: 'bazhongshi',
    pinyinFirstLetter: 'bzs',
  },
  {
    code: '512000',
    name: '资阳市',
    shortName: '资阳',
    pinyin: 'ziyangshi',
    pinyinFirstLetter: 'zys',
  },
  {
    code: '513200',
    name: '阿坝藏族羌族自治州',
    shortName: '阿坝',
    pinyin: 'abacangzuqiangzuzizhizhou',
    pinyinFirstLetter: 'abczqzzzz',
  },
  {
    code: '513300',
    name: '甘孜藏族自治州',
    shortName: '甘孜',
    pinyin: 'ganzicangzuzizhizhou',
    pinyinFirstLetter: 'gzczzzz',
  },
  {
    code: '513400',
    name: '凉山彝族自治州',
    shortName: '凉山',
    pinyin: 'liangshanyizuzizhizhou',
    pinyinFirstLetter: 'lsyzzzz',
  },
  {
    code: '520000',
    name: '贵州省',
    shortName: '贵州',
    pinyin: 'guizhousheng',
    pinyinFirstLetter: 'gzs',
  },
  {
    code: '520100',
    name: '贵阳市',
    shortName: '贵阳',
    pinyin: 'guiyangshi',
    pinyinFirstLetter: 'gys',
  },
  {
    code: '520200',
    name: '六盘水市',
    shortName: '六盘水',
    pinyin: 'liupanshuishi',
    pinyinFirstLetter: 'lpss',
  },
  {
    code: '520300',
    name: '遵义市',
    shortName: '遵义',
    pinyin: 'zunyishi',
    pinyinFirstLetter: 'zys',
  },
  {
    code: '520400',
    name: '安顺市',
    shortName: '安顺',
    pinyin: 'anshunshi',
    pinyinFirstLetter: 'ass',
  },
  {
    code: '520500',
    name: '毕节市',
    shortName: '毕节',
    pinyin: 'bijieshi',
    pinyinFirstLetter: 'bjs',
  },
  {
    code: '520600',
    name: '铜仁市',
    shortName: '铜仁',
    pinyin: 'tongrenshi',
    pinyinFirstLetter: 'trs',
  },
  {
    code: '522300',
    name: '黔西南布依族苗族自治州',
    shortName: '黔西南',
    pinyin: 'qianxinanbuyizumiaozuzizhizhou',
    pinyinFirstLetter: 'qxnbyzmzzzz',
  },
  {
    code: '522600',
    name: '黔东南苗族侗族自治州',
    shortName: '黔东南',
    pinyin: 'qiandongnanmiaozudongzuzizhizhou',
    pinyinFirstLetter: 'qdnmzdzzzz',
  },
  {
    code: '522700',
    name: '黔南布依族苗族自治州',
    shortName: '黔南',
    pinyin: 'qiannanbuyizumiaozuzizhizhou',
    pinyinFirstLetter: 'qnbyzmzzzz',
  },
  {
    code: '530000',
    name: '云南省',
    shortName: '云南',
    pinyin: 'yunnansheng',
    pinyinFirstLetter: 'yns',
  },
  {
    code: '530100',
    name: '昆明市',
    shortName: '昆明',
    pinyin: 'kunmingshi',
    pinyinFirstLetter: 'kms',
  },
  {
    code: '530300',
    name: '曲靖市',
    shortName: '曲靖',
    pinyin: 'qujingshi',
    pinyinFirstLetter: 'qjs',
  },
  {
    code: '530400',
    name: '玉溪市',
    shortName: '玉溪',
    pinyin: 'yuxishi',
    pinyinFirstLetter: 'yxs',
  },
  {
    code: '530500',
    name: '保山市',
    shortName: '保山',
    pinyin: 'baoshanshi',
    pinyinFirstLetter: 'bss',
  },
  {
    code: '530600',
    name: '昭通市',
    shortName: '昭通',
    pinyin: 'zhaotongshi',
    pinyinFirstLetter: 'zts',
  },
  {
    code: '530700',
    name: '丽江市',
    shortName: '丽江',
    pinyin: 'lijiangshi',
    pinyinFirstLetter: 'ljs',
  },
  {
    code: '530800',
    name: '普洱市',
    shortName: '普洱',
    pinyin: 'puershi',
    pinyinFirstLetter: 'pes',
  },
  {
    code: '530900',
    name: '临沧市',
    shortName: '临沧',
    pinyin: 'lincangshi',
    pinyinFirstLetter: 'lcs',
  },
  {
    code: '532300',
    name: '楚雄彝族自治州',
    shortName: '楚雄',
    pinyin: 'chuxiongyizuzizhizhou',
    pinyinFirstLetter: 'cxyzzzz',
  },
  {
    code: '532500',
    name: '红河哈尼族彝族自治州',
    shortName: '红河',
    pinyin: 'honghehanizuyizuzizhizhou',
    pinyinFirstLetter: 'hhhnzyzzzz',
  },
  {
    code: '532600',
    name: '文山壮族苗族自治州',
    shortName: '文山',
    pinyin: 'wenshanzhuangzumiaozuzizhizhou',
    pinyinFirstLetter: 'wszzmzzzz',
  },
  {
    code: '532800',
    name: '西双版纳傣族自治州',
    shortName: '西双版纳',
    pinyin: 'xishuangbannadaizuzizhizhou',
    pinyinFirstLetter: 'xsbndzzzz',
  },
  {
    code: '532900',
    name: '大理白族自治州',
    shortName: '大理',
    pinyin: 'dalibaizuzizhizhou',
    pinyinFirstLetter: 'dlbzzzz',
  },
  {
    code: '533100',
    name: '德宏傣族景颇族自治州',
    shortName: '德宏',
    pinyin: 'dehongdaizujingpozuzizhizhou',
    pinyinFirstLetter: 'dhdzjpzzzz',
  },
  {
    code: '533300',
    name: '怒江傈僳族自治州',
    shortName: '怒江',
    pinyin: 'nujianglisuzuzizhizhou',
    pinyinFirstLetter: 'njlszzzz',
  },
  {
    code: '533400',
    name: '迪庆藏族自治州',
    shortName: '迪庆',
    pinyin: 'diqingcangzuzizhizhou',
    pinyinFirstLetter: 'dqczzzz',
  },
  {
    code: '540000',
    name: '西藏自治区',
    shortName: '西藏',
    pinyin: 'xicangzizhiqu',
    pinyinFirstLetter: 'xczzq',
  },
  {
    code: '540100',
    name: '拉萨市',
    shortName: '拉萨',
    pinyin: 'lasashi',
    pinyinFirstLetter: 'lss',
  },
  {
    code: '540200',
    name: '日喀则市',
    shortName: '日喀则',
    pinyin: 'rikazeshi',
    pinyinFirstLetter: 'rkzs',
  },
  {
    code: '540300',
    name: '昌都市',
    shortName: '昌都',
    pinyin: 'changdushi',
    pinyinFirstLetter: 'cds',
  },
  {
    code: '540400',
    name: '林芝市',
    shortName: '林芝',
    pinyin: 'linzhishi',
    pinyinFirstLetter: 'lzs',
  },
  {
    code: '540500',
    name: '山南市',
    shortName: '山南',
    pinyin: 'shannanshi',
    pinyinFirstLetter: 'sns',
  },
  {
    code: '540600',
    name: '那曲市',
    shortName: '那曲',
    pinyin: 'naqushi',
    pinyinFirstLetter: 'nqs',
  },
  {
    code: '542500',
    name: '阿里地区',
    shortName: '阿里',
    pinyin: 'alidiqu',
    pinyinFirstLetter: 'aldq',
  },
  {
    code: '610000',
    name: '陕西省',
    shortName: '陕西',
    pinyin: 'shanxisheng',
    pinyinFirstLetter: 'sxs',
  },
  {
    code: '610100',
    name: '西安市',
    shortName: '西安',
    pinyin: 'xianshi',
    pinyinFirstLetter: 'xas',
  },
  {
    code: '610200',
    name: '铜川市',
    shortName: '铜川',
    pinyin: 'tongchuanshi',
    pinyinFirstLetter: 'tcs',
  },
  {
    code: '610300',
    name: '宝鸡市',
    shortName: '宝鸡',
    pinyin: 'baojishi',
    pinyinFirstLetter: 'bjs',
  },
  {
    code: '610400',
    name: '咸阳市',
    shortName: '咸阳',
    pinyin: 'xianyangshi',
    pinyinFirstLetter: 'xys',
  },
  {
    code: '610500',
    name: '渭南市',
    shortName: '渭南',
    pinyin: 'weinanshi',
    pinyinFirstLetter: 'wns',
  },
  {
    code: '610600',
    name: '延安市',
    shortName: '延安',
    pinyin: 'yananshi',
    pinyinFirstLetter: 'yas',
  },
  {
    code: '610700',
    name: '汉中市',
    shortName: '汉中',
    pinyin: 'hanzhongshi',
    pinyinFirstLetter: 'hzs',
  },
  {
    code: '610800',
    name: '榆林市',
    shortName: '榆林',
    pinyin: 'yulinshi',
    pinyinFirstLetter: 'yls',
  },
  {
    code: '610900',
    name: '安康市',
    shortName: '安康',
    pinyin: 'ankangshi',
    pinyinFirstLetter: 'aks',
  },
  {
    code: '611000',
    name: '商洛市',
    shortName: '商洛',
    pinyin: 'shangluoshi',
    pinyinFirstLetter: 'sls',
  },
  {
    code: '620000',
    name: '甘肃省',
    shortName: '甘肃',
    pinyin: 'gansusheng',
    pinyinFirstLetter: 'gss',
  },
  {
    code: '620100',
    name: '兰州市',
    shortName: '兰州',
    pinyin: 'lanzhoushi',
    pinyinFirstLetter: 'lzs',
  },
  {
    code: '620200',
    name: '嘉峪关市',
    shortName: '嘉峪关',
    pinyin: 'jiayuguanshi',
    pinyinFirstLetter: 'jygs',
  },
  {
    code: '620300',
    name: '金昌市',
    shortName: '金昌',
    pinyin: 'jinchangshi',
    pinyinFirstLetter: 'jcs',
  },
  {
    code: '620400',
    name: '白银市',
    shortName: '白银',
    pinyin: 'baiyinshi',
    pinyinFirstLetter: 'bys',
  },
  {
    code: '620500',
    name: '天水市',
    shortName: '天水',
    pinyin: 'tianshuishi',
    pinyinFirstLetter: 'tss',
  },
  {
    code: '620600',
    name: '武威市',
    shortName: '武威',
    pinyin: 'wuweishi',
    pinyinFirstLetter: 'wws',
  },
  {
    code: '620700',
    name: '张掖市',
    shortName: '张掖',
    pinyin: 'zhangyeshi',
    pinyinFirstLetter: 'zys',
  },
  {
    code: '620800',
    name: '平凉市',
    shortName: '平凉',
    pinyin: 'pingliangshi',
    pinyinFirstLetter: 'pls',
  },
  {
    code: '620900',
    name: '酒泉市',
    shortName: '酒泉',
    pinyin: 'jiuquanshi',
    pinyinFirstLetter: 'jqs',
  },
  {
    code: '621000',
    name: '庆阳市',
    shortName: '庆阳',
    pinyin: 'qingyangshi',
    pinyinFirstLetter: 'qys',
  },
  {
    code: '621100',
    name: '定西市',
    shortName: '定西',
    pinyin: 'dingxishi',
    pinyinFirstLetter: 'dxs',
  },
  {
    code: '621200',
    name: '陇南市',
    shortName: '陇南',
    pinyin: 'longnanshi',
    pinyinFirstLetter: 'lns',
  },
  {
    code: '622900',
    name: '临夏回族自治州',
    shortName: '临夏',
    pinyin: 'linxiahuizuzizhizhou',
    pinyinFirstLetter: 'lxhzzzz',
  },
  {
    code: '623000',
    name: '甘南藏族自治州',
    shortName: '甘南',
    pinyin: 'gannancangzuzizhizhou',
    pinyinFirstLetter: 'gnczzzz',
  },
  {
    code: '630000',
    name: '青海省',
    shortName: '青海',
    pinyin: 'qinghaisheng',
    pinyinFirstLetter: 'qhs',
  },
  {
    code: '630100',
    name: '西宁市',
    shortName: '西宁',
    pinyin: 'xiningshi',
    pinyinFirstLetter: 'xns',
  },
  {
    code: '630200',
    name: '海东市',
    shortName: '海东',
    pinyin: 'haidongshi',
    pinyinFirstLetter: 'hds',
  },
  {
    code: '632200',
    name: '海北藏族自治州',
    shortName: '海北',
    pinyin: 'haibeicangzuzizhizhou',
    pinyinFirstLetter: 'hbczzzz',
  },
  {
    code: '632300',
    name: '黄南藏族自治州',
    shortName: '黄南',
    pinyin: 'huangnancangzuzizhizhou',
    pinyinFirstLetter: 'hnczzzz',
  },
  {
    code: '632500',
    name: '海南藏族自治州',
    shortName: '海南',
    pinyin: 'hainancangzuzizhizhou',
    pinyinFirstLetter: 'hnczzzz',
  },
  {
    code: '632600',
    name: '果洛藏族自治州',
    shortName: '果洛',
    pinyin: 'guoluocangzuzizhizhou',
    pinyinFirstLetter: 'glczzzz',
  },
  {
    code: '632700',
    name: '玉树藏族自治州',
    shortName: '玉树',
    pinyin: 'yushucangzuzizhizhou',
    pinyinFirstLetter: 'ysczzzz',
  },
  {
    code: '632800',
    name: '海西蒙古族藏族自治州',
    shortName: '海西',
    pinyin: 'haiximengguzucangzuzizhizhou',
    pinyinFirstLetter: 'hxmgzczzzz',
  },
  {
    code: '640000',
    name: '宁夏回族自治区',
    shortName: '宁夏',
    pinyin: 'ningxiahuizuzizhiqu',
    pinyinFirstLetter: 'nxhzzzq',
  },
  {
    code: '640100',
    name: '银川市',
    shortName: '银川',
    pinyin: 'yinchuanshi',
    pinyinFirstLetter: 'ycs',
  },
  {
    code: '640200',
    name: '石嘴山市',
    shortName: '石嘴山',
    pinyin: 'shizuishanshi',
    pinyinFirstLetter: 'szss',
  },
  {
    code: '640300',
    name: '吴忠市',
    shortName: '吴忠',
    pinyin: 'wuzhongshi',
    pinyinFirstLetter: 'wzs',
  },
  {
    code: '640400',
    name: '固原市',
    shortName: '固原',
    pinyin: 'guyuanshi',
    pinyinFirstLetter: 'gys',
  },
  {
    code: '640500',
    name: '中卫市',
    shortName: '中卫',
    pinyin: 'zhongweishi',
    pinyinFirstLetter: 'zws',
  },
  {
    code: '650000',
    name: '新疆维吾尔自治区',
    shortName: '新疆维吾尔',
    pinyin: 'xinjiangweiwuerzizhiqu',
    pinyinFirstLetter: 'xjwwezzq',
  },
  {
    code: '650100',
    name: '乌鲁木齐市',
    shortName: '乌鲁木齐',
    pinyin: 'wulumuqishi',
    pinyinFirstLetter: 'wlmqs',
  },
  {
    code: '650200',
    name: '克拉玛依市',
    shortName: '克拉玛依',
    pinyin: 'kelamayishi',
    pinyinFirstLetter: 'klmys',
  },
  {
    code: '650400',
    name: '吐鲁番市',
    shortName: '吐鲁番',
    pinyin: 'tulufanshi',
    pinyinFirstLetter: 'tlfs',
  },
  {
    code: '650500',
    name: '哈密市',
    shortName: '哈密',
    pinyin: 'hamishi',
    pinyinFirstLetter: 'hms',
  },
  {
    code: '652300',
    name: '昌吉回族自治州',
    shortName: '昌吉',
    pinyin: 'changjihuizuzizhizhou',
    pinyinFirstLetter: 'cjhzzzz',
  },
  {
    code: '652700',
    name: '博尔塔拉蒙古自治州',
    shortName: '博尔塔拉蒙古',
    pinyin: 'boertalamengguzizhizhou',
    pinyinFirstLetter: 'betlmgzzz',
  },
  {
    code: '652800',
    name: '巴音郭楞蒙古自治州',
    shortName: '巴音郭楞蒙古',
    pinyin: 'bayinguolengmengguzizhizhou',
    pinyinFirstLetter: 'byglmgzzz',
  },
  {
    code: '652900',
    name: '阿克苏地区',
    shortName: '阿克苏',
    pinyin: 'akesudiqu',
    pinyinFirstLetter: 'aksdq',
  },
  {
    code: '653000',
    name: '克孜勒苏柯尔克孜自治州',
    shortName: '克孜勒苏柯尔克孜',
    pinyin: 'kezilesukeerkezizizhizhou',
    pinyinFirstLetter: 'kzlskekzzzz',
  },
  {
    code: '653100',
    name: '喀什地区',
    shortName: '喀什',
    pinyin: 'kashidiqu',
    pinyinFirstLetter: 'ksdq',
  },
  {
    code: '653200',
    name: '和田地区',
    shortName: '和田',
    pinyin: 'hetiandiqu',
    pinyinFirstLetter: 'htdq',
  },
  {
    code: '654000',
    name: '伊犁哈萨克自治州',
    shortName: '伊犁哈萨克',
    pinyin: 'yilihasakezizhizhou',
    pinyinFirstLetter: 'ylhskzzz',
  },
  {
    code: '654200',
    name: '塔城地区',
    shortName: '塔城',
    pinyin: 'tachengdiqu',
    pinyinFirstLetter: 'tcdq',
  },
  {
    code: '654300',
    name: '阿勒泰地区',
    shortName: '阿勒泰',
    pinyin: 'aletaidiqu',
    pinyinFirstLetter: 'altdq',
  },
  {
    code: '710000',
    name: '台湾省',
    shortName: '台湾',
    pinyin: 'taiwansheng',
    pinyinFirstLetter: 'tws',
  },
  {
    code: '810000',
    name: '香港特别行政区',
    shortName: '香港',
    pinyin: 'xianggangtebiehangzhengqu',
    pinyinFirstLetter: 'xgtbhzq',
  },
  {
    code: '820000',
    name: '澳门特别行政区',
    shortName: '澳门',
    pinyin: 'aomentebiehangzhengqu',
    pinyinFirstLetter: 'amtbhzq',
  },
];
